### ISSUE TITLE
Voorbeeld data

### ISSUE THREAD

**Issue by rvosa** [thoha/FlorML#2]
Zouden er misschien wat voorbeeldbestanden (liefst gewoon alles?) van de OCR toegevoegd kunnen worden?

**Comment by thoha** [comment]
Zie dit nu pas. Heb je enig idee hoeveel gigabyte dat is ?

**Comment by rvosa** [comment]
Nee, geen idee. Waarschijnlijk wel te behappen met [git-lfs](https://git-lfs.github.com/), toch?

**Comment by thoha** [comment]
Since this is an international community, let me explain in English (the question is "Can the files with the original OCR be added to the repository?"):

Although there are no absolute limits to the size of repositories, [this page](https://help.github.com/articles/what-is-my-disk-quota/) suggests that repositories are better kept under 1 Gb in size, and files under 100 Mb in size, unless you wish to get a warning. 
The complete "compact" version of my data, consisting of the resulting XML files + the scripts + original OCR files + documentation + figures + some other stuff, meant for archiving by supervisors and others, without only little versioning or intermediate files included, is already about 30.5 Gb (!). Most of that amount consists of the original scans, the files with the OCR, some of which are rather large (consistent with 600-1,000 page flora volumes with small text and many images), and about 6,600 images of plants.

If you want to get an idea of the variation in OCR quality (obtained in 2011-2012), find yourself a PDF of one of the early Flora Malesiana volumes (e.g. Series I vol. 6). There are several PDFs floating around on the web. Then use try using the following two options for producing the OCR:
- Standard OCR of Adobe Acrobat Pro (worst; tested up to version 10.0), 
- OCR produced by stand-alone OCR package such as ABBYY FineReader Professional 12 with all required language turned on but none of the user-assisted learning functions (best; it will still miss a lot of special symbols).
